version: "2"

formatters:
  enable:
    - goimports
    - gofumpt

linters:
  default: none
  enable:
  - bodyclose
  - contextcheck
  - dogsled
  - errcheck
  - errname
  - exhaustive
  - goconst
  - gocyclo
  - goprintffuncname
  - gosec
  - govet
  - ineffassign
  - misspell
  - nakedret
  - makezero
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - prealloc
  - predeclared
  - revive
  - spancheck
  - staticcheck
  - unconvert
  - unparam
  - unused
  - whitespace
  settings:
    gosec:
      excludes:
        - G601
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
  exclusions:
    rules:
      - path: (.+)_test.go
        linters:
          - dupl
      - linters:
          - revive
          - stylecheck
        text: dot imports
        source: gomega
      - linters:
          - revive
          - stylecheck
        text: dot imports
        source: ginkgo
      - linters:
          - staticcheck
        text: 'QF1006' # could lift into loop condition
