repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.27.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
- repo: local
  hooks:
  - id: golangci-lint
    name: golangci-lint
    entry: mise run lint-fix
    language: system
    types: [go]
    pass_filenames: false
  - id: go-mod-tidy
    name: go mod tidy
    entry: mise run tidy
    language: system
    types: [go]
    pass_filenames: false
